### ISSUE TITLE
camera to lidar coordinate convertion for another lidar sensor

### ISSUE THREAD

**Issue by a-ngo** [tsinghua-rll/VoxelNet-tensorflow#43]
how did u come up with the matrices for camera and lidar coordinate convertion in config.py?
(__C.MATRIX_P2, __C.MATRIX_T_VELO_2_CAM, __C.MATRIX_R_RECT_0 )

the thing is I want to try the VoxelNet with another lidar sensor but I don't know how to adjust this matrices.

**Comment by xueyingliu** [comment]
@artdengo I have the same question with you, have you already solved it?

**Comment by LinHungShi** [comment]
I think the author just calculated the average of each matrix over all images. The calibration matrices for each image and lidar can be downloaded from [kitti website](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).

**Comment by artdengo** [comment]
@xueyingliu I didn't solve it yet.

@LinHungShi so do you think that it is possible to completely remove the usage of these calibration matrices?? and how would you do that?
because I got my own lidar and label data, that are already calibrated and I assume that images are only used for visualization purposes, no?

**Comment by LinHungShi** [comment]
if you want to detect objects in lidar, you don't need those matrices. calibration is needed because all labels in kitti is in camera coordinate.

**Comment by xueyingliu** [comment]
@LinHungShi really thanks for your reply, now it is clear.
